sudo: required

services:
  - docker

jobs:
  include:
    - stage: Bake
      script:
      - cd jdk-8-alpine/ 
      - docker build -t $DOCKER_USERNAME/maven-alpine-jdk8:1.0 .
      - docker images
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker push $DOCKER_USERNAME/maven-alpine-jdk8:1.0
      
    - stage: Test
      script:
      - docker run -itd -p 8080:8080 --name cool_container $DOCKER_USERNAME/maven-alpine-jdk8:1.0
      - docker ps -a
      after_script:
      - docker stop cool_container
      - docker rm cool_container
